'use strict';
(function(root){
 const normalize=name=>String(name||'').replace(/ (city|town|village|CDP|borough|municipality|zona urbana|comunidad)$/i,'').trim().toUpperCase();
 const validPoint=p=>!!p&&Number.isFinite(p.lat)&&Number.isFinite(p.lon)&&Math.abs(p.lat)<=90&&Math.abs(p.lon)<=180;
 function distance(a,b){if(!validPoint(a)||!validPoint(b))return null;const rad=x=>x*Math.PI/180,lat1=rad(a.lat),lat2=rad(b.lat),dlat=lat2-lat1,dlon=rad(b.lon-a.lon),h=Math.sin(dlat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dlon/2)**2;return 3958.7613*2*Math.atan2(Math.sqrt(h),Math.sqrt(Math.max(0,1-h)));}
 function index(places){const ids=new Map(),names=new Map();for(const p of places){ids.set(p.id,p);const key=p.state+'|'+normalize(p.name);if(!names.has(key))names.set(key,[]);names.get(key).push(p);}return {ids,names};}
 function resolve(location,lookup){const byId=lookup.ids.get(location.place_geoid);if(byId&&byId.state===location.state)return byId;const city=location.state==='HI'&&normalize(location.city)==='HONOLULU'?'URBAN HONOLULU':normalize(location.city);const found=lookup.names.get(location.state+'|'+city)||[];return found.length===1?found[0]:null;}
 function zipCountry(zip){return /^00[679]/.test(zip)?'PR':/^008/.test(zip)?'VI':zip==='96799'?'AS':/^969[123]/.test(zip)?'GU':/^9695/.test(zip)?'MP':'US';}
 function zipOrigin(zip,data){
  const place=data?.places?.[0],country=zipCountry(zip),lat=place?.latitude,lon=place?.longitude;
  if(!/^\d{5}$/.test(zip)||data?.['post code']!==zip||data?.['country abbreviation']!==country||!place||typeof lat!=='string'||!lat.trim()||typeof lon!=='string'||!lon.trim()||typeof place['place name']!=='string'||!place['place name'].trim())throw new Error('ZIP lookup returned invalid location data');
  const origin={name:place['place name'],state:country==='US'?place['state abbreviation']:country,lat:Number(lat),lon:Number(lon),zip};
  if(!validPoint(origin)||!(/^[A-Z]{2}$/.test(origin.state||'')))throw new Error('ZIP lookup returned invalid coordinates or state');return origin;
 }
 function inMarket(person,origin,mode,lookup){const loc=person.location||{};if(mode==='all')return true;if(mode==='SC')return !!origin&&loc.state===origin.state;const radius=Number(mode),d=distance(origin,resolve(loc,lookup));return Number.isFinite(radius)&&radius>=1&&radius<=3000&&d!==null&&d<=radius;}
 function coverage(records,origin,mode,lookup,actionable){const local=records.filter(p=>inMarket(p,origin,mode,lookup)),states=new Map();for(const p of records){const state=p.location?.state||'UNKNOWN';if(!states.has(state))states.set(state,{state,people:0,planning:0});const entry=states.get(state);entry.people++;if(p.events.some(actionable))entry.planning++;}return {people:local.length,planning:local.filter(p=>p.events.some(actionable)).length,unknown_geography:records.filter(p=>!resolve(p.location||{},lookup)).length,states:[...states.values()].sort((a,b)=>b.planning-a.planning||a.state.localeCompare(b.state))};}
 function preference(origin,mode){return {product:'Project A',schema:1,origin:{name:origin.name,state:origin.state,lat:origin.lat,lon:origin.lon,...(origin.zip?{zip:origin.zip}:{}),...(origin.id?{id:origin.id}:{})},mode};}
 function restorePreference(value,lookup){if(!value||value.product!=='Project A'||value.schema!==1||!['all','SC'].includes(value.mode)&&!(Number.isInteger(Number(value.mode))&&Number(value.mode)>=1&&Number(value.mode)<=3000))return null;const o=value.origin;if(!o||typeof o.name!=='string'||o.name.length>160||!validPoint(o))return null;if(o.id){const known=lookup.ids.get(o.id);return known?{origin:known,mode:String(value.mode)}:null;}if(!/^\d{5}$/.test(o.zip||'')||typeof o.state!=='string'||!(/^[A-Z]{2}$/.test(o.state)))return null;return {origin:{name:o.name,state:o.state,lat:o.lat,lon:o.lon,zip:o.zip},mode:String(value.mode)};}
 const api={normalize,distance,index,resolve,zipCountry,zipOrigin,inMarket,coverage,preference,restorePreference};if(typeof module==='object'&&module.exports)module.exports=api;else root.ProjectTerritory=api;
})(typeof window==='undefined'?globalThis:window);
