'use strict';
const assert=require('node:assert/strict'), fs=require('node:fs');
const Pilot=require('./pilot.js');
const people=JSON.parse(fs.readFileSync('catalog.json')).records,p=people[0];
const now=Date.parse('2026-10-05T14:00:00Z');
const review={person_id:p.id,reviewer_id:'qa-reviewer-one',person_name:'Untrusted name',company:'Untrusted company',rating:'Needs evidence',note:'QA fixture only: <script>unsafe</script>',recorded_at:'2026-10-05T13:00:00Z',score:70,scoring_version:'money-in-motion-v3',source_accessions:[p.events[0].accession]};
const payload=feedback=>({product:'Project A',schema_version:2,feedback});
const validated=Pilot.validate(payload([review]),people,now);
assert.equal(validated[0].person_name,p.person_name);assert.equal(validated[0].company,p.company);assert.equal(validated[0].note,review.note);
assert.equal(Pilot.merge(validated,validated).length,1);
assert.equal(Pilot.merge(validated,[{...validated[0],reviewer_id:'qa-reviewer-two'}]).length,2);
const newer={...validated[0],recorded_at:'2026-10-05T13:30:00.000Z',note:'New review'};
assert.equal(Pilot.merge([newer],validated)[0].note,'New review');
assert.equal(Pilot.merge(validated,[newer])[0].note,'New review');
for(const change of [{person_id:'unknown'},{rating:'Buy'},{note:'x'.repeat(1001)},{reviewer_id:'<img>'},{recorded_at:'invalid'},{recorded_at:'2026-10-06T13:00:00Z'},{score:101},{score:NaN},{source_accessions:['0000000000-26-999999']},{source_accessions:['javascript:alert(1)']}])assert.throws(()=>Pilot.validate(payload([review,{...review,...change}]),people,now));
assert.throws(()=>Pilot.validate({...payload([review]),schema_version:999},people,now));
assert.throws(()=>Pilot.validate({...payload([review]),product:'Another product'},people,now));
assert.throws(()=>Pilot.validate(payload(Array(1001).fill(review)),people,now));
const legacy={...review};delete legacy.reviewer_id;
assert.equal(Pilot.validate({product:'Project A',feedback:[legacy]},people,now)[0].reviewer_id,'legacy-unknown');
console.log('Pilot import checks passed: provenance validation, atomic rejection, reviewer separation, deduplication and newer-review retention.');
