(function(root){
'use strict';
const definitions=[
 {id:'LIQUIDITY',label:'Completed stock sale',sources:'SEC Form 4 · code S disposition',why:'Equity monetization may make diversification, tax coordination and liquidity planning timely.',limit:'Gross shares × price is not net proceeds, wealth or available cash. Planned trades reduce inferred urgency.',themes:['Diversification','Tax coordination','Liquidity planning'],stages:['DISCLOSED']},
 {id:'EXECUTIVE_TRANSITION',label:'Executive retirement / departure',sources:'SEC Form 8-K Item 5.02 · transition agreements',why:'A career transition may change equity vesting, benefits, retirement timing and compensation.',limit:'Announced or conditional departures are not completed transitions. Contract terms do not prove payment.',themes:['Retirement transition','Executive compensation','Benefit coordination'],stages:['ANNOUNCED','CONDITIONAL','COMPLETED']},
 {id:'BUSINESS_EXIT',label:'Business sale / acquisition',sources:'SEC Form 8-K Item 2.01 · merger documents · official closing announcements',why:'A named founder’s or owner’s verified company exit may create diversification, tax, succession and estate-planning decisions.',limit:'Company deal value is not individual proceeds. Founder status does not prove a stake at closing. Confirm ownership, individual consideration and completion.',themes:['Business succession','Diversification','Tax coordination','Estate planning'],stages:['ANNOUNCED','COMPLETED']},
 {id:'PUBLIC_OFFERING',label:'IPO / secondary offering',sources:'SEC S-1 / prospectus · selling-shareholder disclosures',why:'A named selling shareholder or newly public equity position may need concentration and tax planning.',limit:'An offering, registered shares or lockup expiry does not establish a sale. Individual participation requires evidence.',themes:['Concentrated equity','Diversification','Tax coordination'],stages:['REGISTERED','COMPLETED']},
 {id:'OWNERSHIP_CHANGE',label:'Major ownership change',sources:'SEC Schedule 13D / 13G amendments',why:'A material stake change can flag a business or concentrated-equity transition worth investigating.',limit:'A percentage change may reflect dilution, transfers or a denominator change. It does not establish cash proceeds.',themes:['Concentrated equity','Risk management','Business succession'],stages:['DISCLOSED']},
 {id:'PROPOSED_SALE',label:'Proposed stock sale',sources:'SEC Form 144',why:'A proposed sale provides an early prompt to monitor future monetization and equity-planning context.',limit:'A notice is not a completed sale. Proposed market value is excluded from sale totals and convergence points.',themes:['Concentrated equity','Diversification','Tax coordination'],stages:['PROPOSED']},
 {id:'PROPERTY_SALE',label:'Significant property sale',sources:'Official recorded deed / transfer record · documented ownership',why:'A commercial or investment-property exit may create reinvestment, tax and estate-planning decisions.',limit:'Confirm the seller’s identity and ownership. Gross consideration is not net proceeds; debt and costs may be unknown.',themes:['Reinvestment planning','Tax coordination','Estate planning'],stages:['COMPLETED']},
 {id:'LOTTERY_AWARD',label:'Publicly named lottery award',sources:'Official lottery announcement identifying the winner',why:'A documented windfall may create tax, payout, estate and long-term cash-flow planning needs.',limit:'Anonymous winners and retailer locations are not prospects. Advertised jackpots and annuities are not cash received.',themes:['Tax coordination','Liquidity planning','Estate planning','Risk management'],stages:['ANNOUNCED']},
 {id:'ESTATE_DISTRIBUTION',label:'Documented inheritance',sources:'Lawfully public probate / distribution records identifying a beneficiary',why:'A documented distribution may change asset allocation, inherited-asset administration and estate-planning needs.',limit:'An obituary or opened estate does not prove an inheritance. Estate value is not a beneficiary’s receipt; avoid bereavement-based outreach.',themes:['Inherited-asset planning','Tax coordination','Estate planning'],stages:['BENEFICIARY_IDENTIFIED','DISTRIBUTION_DOCUMENTED']}
];
const byId=Object.fromEntries(definitions.map(d=>[d.id,d]));
function definition(event){return byId[event.trigger_type||event.classification]||null;}
function forPerson(person){return [...new Map(person.events.map(e=>{const d=definition(e);return d?[d.id,d]:null;}).filter(Boolean)).values()];}
function actionable(e){if(['LIQUIDITY','EXECUTIVE_TRANSITION'].includes(e.classification))return true;return Boolean(e.reviewed_trigger&&['BUSINESS_EXIT','PUBLIC_OFFERING','PROPERTY_SALE'].includes(e.trigger_type)&&e.stage==='COMPLETED'||e.reviewed_trigger&&e.trigger_type==='LOTTERY_AWARD'&&e.stage==='ANNOUNCED'||e.reviewed_trigger&&e.trigger_type==='ESTATE_DISTRIBUTION'&&e.stage==='DISTRIBUTION_DOCUMENTED');}
const api={definitions,byId,definition,forPerson,actionable};
if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.ProjectTriggers=api;
})(typeof window!=='undefined'?window:globalThis);
